In [1]:
import pandas as pd
import numpy as np

In [11]:
df=pd.read_csv('IMDB Dataset.csv')

In [12]:
df.head() # This is the data we got

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [13]:
# One review
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text Cleaning

1. Sample 10000 rows
2. Remove html tags
3. Remove special characters
4. Converting every thing to lower case
5. Removing Stop words
6. Stemming

In [14]:
df=df.sample(10000)

In [15]:
df.shape

(10000, 2)

In [18]:
df.head()

                                                  review sentiment
1750   I must say that I am fairly disappointed by th...  negative
38342  Ever heard of a taiwanese horror movie? Or any...  negative
19745  How do I describe the horrors?!!! First, some ...  negative
29191  The thing which makes "Fire" even more appeali...  positive
48684  "Erendira" is a film from Mexico that is rarel...  positive

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 10000 entries, 1750 to 41463
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  str
 1   sentiment  10000 non-null  str
dtypes: str(2)
memory usage: 12.7 MB

In [ ]:
df = df.replace({'sentiment':{'positive':1 ,'negative':0}}) # We Binary encoded the sentiment Column

In [20]:
df.head()

                                                  review sentiment
1750   I must say that I am fairly disappointed by th...         0
38342  Ever heard of a taiwanese horror movie? Or any...         0
19745  How do I describe the horrors?!!! First, some ...         0
29191  The thing which makes "Fire" even more appeali...         1
48684  "Erendira" is a film from Mexico that is rarel...         1

### ***Using REGEX To Clean the data***

In [21]:

import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

"How do I describe the horrors?!!! First, some points: First, this review should be taken with a grain of salt -- I saw this over 20 years ago, when I was a boy, at the Museum of Modern Art in New York City.Secondly, I am giving away some scenes and plot points. However, it does not have much of a plot.Finally, I don't enjoy these type of art films anyway.This film was directed by proto-auteur Luis Bunuel. He was a surrealist and dadaist. These were modernist themes or movements popular critically in the 1920's and early 1930's. Surealism was the school of art that made things hyper-real, yet often had Freudian symbolism. Dadaism is based on what is supposedly the first word made by an infant -- Dada, or father.Made in black and white, it was also made by a band of communists (or as they preferred the term, socialists). Bunuel and his group of fellow film-makers and artistes had been working on a number of symbolic ideas and issues in Spain and France between the world wars.Dadaism and surrealism influenced a lot of artists -- The Police (Doo doo doo da), poet Arthur Rambaud, Edvard Munch (The Scream), Rene Magritte (floating hats in space), Salvador Dali (melting clocks), and even Hitchcock (Psycho). No Norman Rockwell.Here's what I recall most about this film: a girl meets up with a cow; her eye gets slashed by a razor; clownish men cavort in a meadow. There is not, as I said, much of a plot, but then again, that must be the point.This was attacked as porn back then, and would be again today. One of the trade-marks of surrealism is a significant anti-feminism."

In [22]:
# Function to clean html tags
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [23]:
df['review']=df['review'].apply(clean_html)

In [24]:
# converting everything to lower

def convert_lower(text):
    return text.lower()

In [25]:
df['review']=df['review'].apply(convert_lower)

In [26]:
# function to remove special characters

def remove_special(text):
    x=''
    
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x + ' '
    return x

In [27]:
remove_special(' th%e @ classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare. forget pretty pictures painted for mainstream audiences, f')

' th e   classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary  it focuses mainly on emerald city  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  em city is home to many  aryans  muslims  gangstas  latinos  christians  italians  irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare  forget pretty pictures painted for mainstream audiences  f'

In [28]:
df['review']=df['review'].apply(remove_special)

In [29]:
# Remove the stop words
import nltk

In [30]:
from nltk.corpus import stopwords

In [32]:
nltk.download('stopwords')
stopwords.words('english')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Pradhuman\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [33]:
df

                                                  review sentiment
1750   i must say that i am fairly disappointed by th...         0
38342  ever heard of a taiwanese horror movie  or any...         0
19745  how do i describe the horrors     first  some ...         0
29191  the thing which makes  fire  even more appeali...         1
48684   erendira  is a film from mexico that is rarel...         1
...                                                  ...       ...
10292  i hate plane crash movies   all of them  in fa...         0
13320  i m not american  but meatballs still really h...         1
8670   i rate this 10 out of 10  why   it offers insi...         1
29925  ok i caught this film halfway through  but oh ...         0
41463  i loved this movie  it was almost the same as ...         1

[10000 rows x 2 columns]

In [34]:

def remove_stopwords(text):
    x=[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [35]:
df['review']=df['review'].apply(remove_stopwords)

In [36]:
df

                                                  review sentiment
1750   [must, say, fairly, disappointed, horror, movi...         0
38342  [ever, heard, taiwanese, horror, movie, taiwan...         0
19745  [describe, horrors, first, points, first, revi...         0
29191  [thing, makes, fire, even, appealing, watch, a...         1
48684  [erendira, film, mexico, rarely, talked, film,...         1
...                                                  ...       ...
10292  [hate, plane, crash, movies, fact, hate, passi...         0
13320  [american, meatballs, still, really, hits, may...         1
8670   [rate, 10, 10, offers, insight, something, bar...         1
29925  [ok, caught, film, halfway, oh, dear, god, sou...         0
41463  [loved, movie, almost, first, cabin, lake, ins...         1

[10000 rows x 2 columns]

In [37]:
# Perform stemming

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [38]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [39]:
stem_words(['I','loved','loving','it'])

['i', 'love', 'love', 'it']

In [40]:
df['review']=df['review'].apply(stem_words)

In [41]:
df

                                                  review sentiment
1750   [must, say, fairli, disappoint, horror, movi, ...         0
38342  [ever, heard, taiwanes, horror, movi, taiwanes...         0
19745  [describ, horror, first, point, first, review,...         0
29191  [thing, make, fire, even, appeal, watch, apart...         1
48684  [erendira, film, mexico, rare, talk, film, exi...         1
...                                                  ...       ...
10292  [hate, plane, crash, movi, fact, hate, passion...         0
13320  [american, meatbal, still, realli, hit, mayb, ...         1
8670   [rate, 10, 10, offer, insight, someth, bare, u...         1
29925  [ok, caught, film, halfway, oh, dear, god, sou...         0
41463  [love, movi, almost, first, cabin, lake, inste...         1

[10000 rows x 2 columns]

In [42]:
# Join back

def join_back(list_input):
    return " ".join(list_input)

In [43]:
df['review']=df['review'].apply(join_back)

In [44]:
df['review']

1750     must say fairli disappoint horror movi get sca...
38342    ever heard taiwanes horror movi taiwanes movi ...
19745    describ horror first point first review taken ...
29191    thing make fire even appeal watch apart magic ...
48684    erendira film mexico rare talk film exist low ...
                               ...
10292    hate plane crash movi fact hate passion first ...
13320    american meatbal still realli hit mayb sweet s...
8670     rate 10 10 offer insight someth bare understan...
29925    ok caught film halfway oh dear god sound like ...
41463    love movi almost first cabin lake instead kill...
Name: review, Length: 10000, dtype: str

In [45]:
X=df.iloc[:,0:1].values

In [46]:
X.shape

(10000, 1)

In [47]:
from sklearn.feature_extraction.text import CountVectorizer  # This class is used to find the Top words in data 
 # and make features based on the top words as Columns and if row contains that Word we get binary 1 otherwise 0. Done this for 2500 Features
cv=CountVectorizer(max_features=2500)

In [48]:
X=cv.fit_transform(df['review']).toarray()

In [49]:
X.shape

(10000, 2500)

In [54]:
X[0].mean()

np.float64(0.0148)

In [55]:
y=df.iloc[:,-1].values

In [66]:
y = y.astype(np.int32)

In [67]:
y.shape

(10000,)

In [41]:
# X,y
# Training set
# Test Set(Already know the result)

In [68]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [69]:
X_train.shape

(8000, 2500)

In [70]:
X_test.shape

(2000, 2500)

In [71]:
y_train.shape

(8000,)

In [72]:
y_test.shape

(2000,)

In [73]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [74]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [75]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB()

In [76]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

In [77]:
y_test.shape

(2000,)

In [78]:
y_pred1.shape

(2000,)

In [79]:
from sklearn.metrics import accuracy_score

In [80]:
print("Gaussian",accuracy_score(y_test,y_pred1))
print("Multinomial",accuracy_score(y_test,y_pred2))
print("Bernaulli",accuracy_score(y_test,y_pred3))

Gaussian 0.719
Multinomial 0.854
Bernaulli 0.8535

### We see that Gaussian Naive Bayes Model performed the worst among the others
- Thus the assumptions that the Features are Normally distributed is Wrong.