**We will Learn How to Encode our Categorical Features and Target Variable**

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('customer.csv')
print(df.head())

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

### We will work on Only Ordinal and Label Encoding For now, later on we can update the file by using 1 hot encoding on Gender Feature and then finally using ColumnTransformer to build a pipeline to complete all encoding at once

In [22]:
X = df.iloc[:,2:4]
y = df.iloc[:,-1]

In [23]:
print(X['review'].value_counts())

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [24]:
print(X['education'].value_counts())

education
PG        18
School    16
UG        16
Name: count, dtype: int64

- We have three types of reviews having order good > average > poor
- We have three categories of education order PG > UG > School

In [25]:
# Let us train/test split from start itself to prevent Data Leakage
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.3 , random_state = 0)

In [26]:
# Let us make OrdinalEncoder object
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

# Let us fit and transform the Training Feature data
X_train_encoded = pd.DataFrame(oe.fit_transform(X_train) , columns = X_train.columns)
X_test_encoded = pd.DataFrame(oe.transform(X_test) , columns = X_test.columns)

In [27]:
# Let us take a loot at it
print(f"Before Encoding -> \n{X_train['education'].head(10)}")
print(f"After Encoding -> \n{X_train_encoded['education'].head(10)}")

Before Encoding ->
7     School
14        PG
45        PG
48        UG
29        UG
15        UG
30        UG
32        UG
16        UG
42        PG
Name: education, dtype: str
After Encoding ->
0    0.0
1    2.0
2    2.0
3    1.0
4    1.0
5    1.0
6    1.0
7    1.0
8    1.0
9    2.0
Name: education, dtype: float64

In [28]:
print(y_train)

7     Yes
14    Yes
45    Yes
48    Yes
29    Yes
15     No
30     No
32    Yes
16    Yes
42    Yes
20    Yes
43     No
8      No
13     No
25     No
5     Yes
17    Yes
40     No
49     No
1      No
12     No
37    Yes
24    Yes
6      No
23     No
36    Yes
21     No
19    Yes
9     Yes
39     No
46     No
3      No
0      No
47    Yes
44     No
Name: purchased, dtype: str

In [29]:
# Now let us Label Encode the target Variable
le = LabelEncoder() # it does not need any parameter
y_train_encoded = pd.Series(le.fit_transform(y_train) , index = y_train.index)
y_test_encoded = pd.Series(le.transform(y_test) , index = y_test.index)

In [30]:
print(y_train_encoded.head(10))

7     1
14    1
45    1
48    1
29    1
15    0
30    0
32    1
16    1
42    1
dtype: int64

### Conclusion 
- We encoded the Ordinal Features using OrdinalEncoder
- We encoded the Target Variable using LabelEncoder

### ***Next Up***
- We will learn how to Encode Nominal Features Using 1-Hot Encoding Technique
- Finally we build ColumnTransformer pipeline to encode every type of Columns as we want

### To Learn One Hot Encoding We firstly import a new dataset of car sales details

In [31]:
df = pd.read_csv('cars.csv')
print(df.head())

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

**This dataSet has 4 Features among which brand, fuel and owner features are Nominal Categorical**

In [32]:
# Let us check the counts of each unique category
print(f"Number of Each Unique Cars ->\n{df['brand'].value_counts()}")

Number of Each Unique Cars ->
brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [33]:
# Number of unique cars
print(df['brand'].nunique())

32

In [34]:
print(df['fuel'].value_counts())  # 4 categories

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [35]:
print(df['owner'].value_counts()) # 5 categories

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

### ***1. ONE HOT ENCODING USING PANDAS***

In [36]:
pd.get_dummies(df[['fuel','owner']] , drop_first=True)

,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,True,False,False,False,False,False,False
1,True,False,False,False,True,False,False
2,False,False,True,False,False,False,True
3,True,False,False,False,False,False,False
4,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...
8123,False,False,True,False,False,False,False
8124,True,False,False,True,False,False,False
8125,True,False,False,False,False,False,False
8126,True,False,False,False,False,False,False
8127,True,False,False,False,False,False,False

In [37]:
import numpy as np

In [38]:
pd.get_dummies(df[['fuel','owner']] , drop_first=True , dtype=np.int32)

,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,1,0,0,0,0,0,0
1,1,0,0,0,1,0,0
2,0,0,1,0,0,0,1
3,1,0,0,0,0,0,0
4,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...
8123,0,0,1,0,0,0,0
8124,1,0,0,1,0,0,0
8125,1,0,0,0,0,0,0
8126,1,0,0,0,0,0,0
8127,1,0,0,0,0,0,0

### This gives us data of dummy columns of the encoded columns
- It is very rarely used
- We generally use sklearn OneHotEncoder()

### ***2. OneHotEncoder() scikit-learn***

In [39]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,:4] , df.iloc[:,-1] , test_size=.3)
X_train.reset_index(drop=True, inplace=True)
X_test.reset_index(drop=True, inplace=True)

In [40]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
ohe = OneHotEncoder(drop='first',sparse_output=False, dtype=np.int32)

ohe.fit_transform(X_train[['fuel']])

array([[1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       ...,
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1]], shape=(5689, 3), dtype=int32)

- See we got 3 columns since we dropped the first column also

In [41]:
X_train_encoded = ohe.fit_transform(X_train[['fuel','owner']])
X_test_encoded = ohe.transform(X_test[['fuel','owner']])

- Used to tranform 2 Features with 9 categories - 2 = 7 total

In [42]:
ohe.get_feature_names_out() # This gives us the newly created dummy features name!! Used to make the Dataframe

array(['fuel_Diesel', 'fuel_LPG', 'fuel_Petrol',
       'owner_Fourth & Above Owner', 'owner_Second Owner',
       'owner_Test Drive Car', 'owner_Third Owner'], dtype=object)

### This gives us an array, we can use merge the non encoded features and then encoded features?

In [43]:
dummy_train_df = pd.DataFrame(X_train_encoded , columns=ohe.get_feature_names_out())
dummy_test_df = pd.DataFrame(X_test_encoded , columns=ohe.get_feature_names_out())

In [44]:
# Now Merge with the original Train and test df while dropping fuel and Owner column from original

final_train = pd.concat([X_train.drop(['fuel','owner'],axis=1) , dummy_train_df] , axis = 1)
final_test = pd.concat([X_test.drop(['fuel','owner'],axis=1) , dummy_test_df] , axis = 1)

In [45]:
print(final_train.head(5))

        brand  km_driven  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0  Volkswagen      18000            1         0            0
1      Maruti      30000            0         0            1
2       Honda      20000            0         0            1
3        Ford      35000            1         0            0
4      Jaguar       9000            1         0            0

   owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                           0                   0                     0
1                           0                   0                     0
2                           0                   0                     0
3                           0                   0                     0
4                           0                   0                     0

   owner_Third Owner
0                  0
1                  0
2                  0
3                  0
4                  0

### HOW TO Encode only Important Variables while labelling others as uncommon or others

In [46]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [47]:
# Let us just pick TOP 10 brands as unique brands(categories) and label rest as others
threshold = 100
count = df['brand'].value_counts()

less_count_brands = count[count<threshold].index

In [48]:
pd.get_dummies(df['brand'].replace(less_count_brands , 'uncommon') , dtype=np.int32).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
4488,0,0,0,0,0,0,0,0,0,1,0,0,0
7457,0,0,0,0,0,0,0,0,0,1,0,0,0
53,0,0,0,0,0,0,1,0,0,0,0,0,0
6128,0,0,0,0,0,0,1,0,0,0,0,0,0
4724,0,0,0,0,0,0,0,0,0,1,0,0,0

### ***This is how we Encode Large Categories Features***

- The most effective way to jump all this nonsense is by using ColumnTransformer

In [49]:
df = pd.read_csv('covid_toy.csv')
print(df.head())

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    str
 2   fever      90 non-null     float64
 3   cough      100 non-null    str
 4   city       100 non-null    str
 5   has_covid  100 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 6.7 KB

- We see 10 missing values in fever column. So we will fill those using SimpleImputer just to go with the workflow

In [59]:
# Let us check if outliers are there in Fever column
df['fever'].describe()

count     90.000000
mean     100.844444
std        2.054926
min       98.000000
25%       99.000000
50%      101.000000
75%      102.750000
max      104.000000
Name: fever, dtype: float64

- There are No Outliers so we will Impute with mean fever only

In [51]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [86]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1], test_size=.2 , random_state=0)
X_train.reset_index(drop=True,inplace=True)
X_test.reset_index(drop=True,inplace=True)
y_train.reset_index(drop=True , inplace=True)
y_test.reset_index(drop=True , inplace=True)

In [87]:
print(f"X_train -> {X_train.shape}")
print(f"y_train -> {y_train.shape}")
print(f"X_test -> {X_test.shape}")
print(f"y_test -> {y_test.shape}")

X_train -> (80, 5)
y_train -> (80,)
X_test -> (20, 5)
y_test -> (20,)

In [68]:
# Let us look at the Ordinal Feature and the flow of it
print(X_train['cough'].value_counts())
print(X_train['city'].value_counts())

cough
Mild      48
Strong    32
Name: count, dtype: int64
city
Bangalore    25
Kolkata      23
Delhi        19
Mumbai       13
Name: count, dtype: int64

- So we got two categories where Strong > Mild
- As for Nominal Categorical columns we don't need to specify the trend

### ***AAM ZINDAGI***

**Simple Imputing Fever Feature**

In [69]:
# Simple Impute the fever column to fill the null values
si = SimpleImputer(strategy='mean') # we will impute with mean fever
X_train['fever'] = si.fit_transform(X_train[['fever']]) # fit transform for one column, we need to pass DataFrame
X_test['fever'] = si.transform(X_test[['fever']])

In [70]:
print(X_train['fever'].isna().sum()) # See we have imputed the Nulls

0

**Label Encoding Target Variable**

In [72]:
# Using label Encoder On Target Variable
le = LabelEncoder()
y_train_encoded = pd.Series(le.fit_transform(y_train))
y_test_encoded = pd.Series(le.fit_transform(y_test))

**Ordinal Encoding Cough Feature**

In [75]:
# Now let us Encode the Ordinal Columns
oe = OrdinalEncoder(categories=[['Mild','Strong']] , dtype=np.int32)
X_train_ord = pd.DataFrame(oe.fit_transform(X_train[['cough']]), columns=X_train[['cough']].columns)
X_test_ord = pd.DataFrame(oe.transform(X_test[['cough']]), columns=X_test[['cough']].columns)

In [76]:
print(X_train_ord)

    cough
0       0
1       1
2       0
3       1
4       0
..    ...
75      1
76      0
77      0
78      0
79      1

[80 rows x 1 columns]

**Nominal Encoding (One Hot Encoding) Gender and City Columns**

In [77]:
ohe = OneHotEncoder(drop='first' , sparse_output=False , dtype=np.int32)

X_train_ohe = pd.DataFrame(ohe.fit_transform(X_train[['gender','city']]), columns = ohe.get_feature_names_out())
X_test_ohe = pd.DataFrame(ohe.transform(X_test[['gender','city']]), columns = ohe.get_feature_names_out())

### ***Concatenating All the DataFrames With Original DataFrame***

In [79]:
X_train_encode = pd.concat([X_train_ohe , X_train_ord] , axis=1)
X_test_encode = pd.concat([X_test_ohe , X_test_ord] , axis=1)

In [80]:
final_train = pd.concat([X_train.drop(['gender','city','cough'],axis=1), X_train_encode],axis=1)
final_test = pd.concat([X_train.drop(['gender','city','cough'],axis=1), X_train_encode],axis=1)

In [81]:
print(final_train)

    age  fever  gender_Male  city_Delhi  city_Kolkata  city_Mumbai  cough
0    22   99.0            0           0             0            0      0
1    56  104.0            0           0             0            0      1
2    31   98.0            0           0             1            0      0
3    75  104.0            0           1             0            0      1
4    72   99.0            1           0             0            0      0
..  ...    ...          ...         ...           ...          ...    ...
75   51  101.0            0           0             1            0      1
76   65   99.0            1           0             0            0      0
77   42  104.0            1           0             0            1      0
78   18  104.0            0           0             0            0      0
79   20  102.0            1           1             0            0      1

[80 rows x 7 columns]

In [83]:
print(y_train_encoded)

0     1
1     1
2     0
3     0
4     0
     ..
75    1
76    0
77    0
78    0
79    0
Length: 80, dtype: int64

### ***Thus we finally Encoded our all the columns (Such a hectic JOB to do )***

### ***MENTOS ZINDAGI***

In [93]:
# Now We will work with ColumnTransformer class transformer
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('impute_fever' , SimpleImputer(strategy='mean') , ['fever']),
    ('onehotencode' , OneHotEncoder(drop='first' , sparse_output=False , dtype=np.int32) , ['gender','city']),
    ('ordinal' , OrdinalEncoder(categories=[['Mild','Strong']] , dtype=np.int32) , ['cough'])
] , remainder= 'passthrough')

In [94]:
transformer.set_output(transform='pandas')
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)

In [95]:
print(X_train_transformed)

    impute_fever__fever  onehotencode__gender_Male  onehotencode__city_Delhi  \
0                  99.0                          0                         0
1                 104.0                          0                         0
2                  98.0                          0                         0
3                 104.0                          0                         1
4                  99.0                          1                         0
..                  ...                        ...                       ...
75                101.0                          0                         0
76                 99.0                          1                         0
77                104.0                          1                         0
78                104.0                          0                         0
79                102.0                          1                         1

    onehotencode__city_Kolkata  onehotencode__city_Mumbai  ordinal__cough  \
0                            0                          0               0
1                            0                          0               1
2                            1                          0               0
3                            0                          0               1
4                            0                          0               0
..                         ...                        ...             ...
75                           1                          0               1
76                           0                          0               0
77                           0                          1               0
78                           0                          0               0
79                           0                          0               1

    remainder__age
0               22
1               56
2               31
3               75
4               72
..             ...
75              51
76              65
77              42
78              18
79              20

[80 rows x 7 columns]

### ***This is how we do it***